name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  http_parser: ^4.0.2
  camera: ^0.11.0+1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  path: ^1.9.0
  go_router: ^14.0.0
  excel: ^4.0.6
  csv: ^6.0.0
  image_picker: ^1.0.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
